/**
 * Verdict envelope returned by `review.start`.
 *
 * STRICT (DESIGN-PRINCIPLES.md §2 — citations are mandatory): the schema
 * enforces `citations.min(1)`. Don't loosen it. The renderer's VerdictCard
 * also gates on this — no card renders without at least one citation.
 */

import { z } from "zod";

export const VerdictLevel = z.enum(["GREEN", "YELLOW", "RED"]);
export type VerdictLevel = z.infer<typeof VerdictLevel>;

export const InstructionKind = z.enum([
  "sol-transfer",
  "spl-transfer",
  "spl-approve",
  "spl-set-authority",
  "spl-close-account",
  "system-create-account",
  "jupiter-swap",
  "magic-eden",
  "unknown",
]);
export type InstructionKind = z.infer<typeof InstructionKind>;

/** A single decoded instruction, in renderer-ready form. */
export const DecodedInstruction = z.object({
  kind: InstructionKind,
  /** Plain-English summary, e.g. "Transfer 0.5 SOL to 7m4Q…aB9P". */
  summary: z.string(),
  /** Solana program id this instruction targets. */
  programId: z.string(),
  /** Arbitrary structured fields the renderer can surface. */
  details: z.record(z.string(), z.union([z.string(), z.number()])),
});
export type DecodedInstruction = z.infer<typeof DecodedInstruction>;

/** Balance change for one account, in human units. */
export const BalanceDelta = z.object({
  account: z.string(),
  /** "SOL" for native, otherwise the SPL mint or symbol. */
  asset: z.string(),
  /** Signed delta in human units (already divided by decimals). */
  delta: z.number(),
});
export type BalanceDelta = z.infer<typeof BalanceDelta>;

export const VerdictExplanation = z.object({
  /** qvac = generated by the local explainer model; deterministic = safe fallback. */
  source: z.enum(["qvac", "deterministic"]),
  /** Machine-readable provenance for logs and subtle UI copy. */
  status: z.enum([
    "ready",
    "fallback",
    "model-missing",
    "runtime-missing",
    "invalid-output",
    "runtime-error",
  ]),
  title: z.string().min(1),
  plainEnglish: z.string().min(1),
  risks: z.array(z.string().min(1)).max(4),
  recommendation: z.string().min(1),
  model: z.string().nullable(),
});
export type VerdictExplanation = z.infer<typeof VerdictExplanation>;

export const Verdict = z.object({
  id: z.string().uuid(),
  level: VerdictLevel,
  summary: z.string().min(1),
  explanation: VerdictExplanation,
  citations: z.array(z.string().min(1)).min(1),
  instructions: z.array(DecodedInstruction),
  deltas: z.array(BalanceDelta),
  /** "Simulation · history" / "Vision · OCR" — the meta strip on the card. */
  meta: z.string().min(1),
  createdAt: z.number().int().nonnegative(),
});
export type Verdict = z.infer<typeof Verdict>;

export const ReviewRecordStatus = z.enum(["pending", "signed", "blocked"]);
export type ReviewRecordStatus = z.infer<typeof ReviewRecordStatus>;

export const ReviewRecord = z.object({
  id: z.string().uuid(),
  status: ReviewRecordStatus,
  verdict: Verdict,
  signature: z.string().nullable(),
  createdAt: z.number().int().nonnegative(),
  updatedAt: z.number().int().nonnegative(),
});
export type ReviewRecord = z.infer<typeof ReviewRecord>;
